import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/NavBar";
import { AuthProvider } from "../AuthProvider";
import OfflineNotice from "@/components/OfflineNotice";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Click2Canteen",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <OfflineNotice/>
          <NavBar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
