import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import AdminLayout from "@/components/AdminLayout/AdminLayout";
import { getUser } from "@/lib/data/user/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminLayout user={user}>{children}</AdminLayout>
      </body>
    </html>
  );
}
