import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminNavBar from "@/components/AdminNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminNavBar />
        {/* Add a wrapper with left margin equal to drawer width */}
        <main style={{ marginLeft: "250px" }}>{children}</main>
      </body>
    </html>
  );
}
