import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import ResponsiveDrawer from "@/components/Admin-Versions/V-1 Set /ResponsiveDrawer"; // or "@/components/ResponsiveDrawer"

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import StyledRoot from "./StyledRoot";
import AppLayout from "@/components/Admin-Versions/V-1 Set /AppLayout";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <StyledRoot>
            <AppLayout>
              <ResponsiveDrawer>{children}</ResponsiveDrawer>
            </AppLayout>
          </StyledRoot>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
